-- liquibase formatted sql

-- changeset james.maes:0001-01
-- comment: Create master_project table - top-level logical software system
CREATE TABLE master_project (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(200) NOT NULL,
   description VARCHAR(2000),
   status VARCHAR(50) NOT NULL,
   goals_json VARCHAR(10000),
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_master_project PRIMARY KEY (id)
);

-- changeset james.maes:0001-02
-- comment: Create repository table - git repository attached to a master project
CREATE TABLE repository (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT NOT NULL,
   name VARCHAR(200) NOT NULL,
   git_url VARCHAR(500) NOT NULL,
   role VARCHAR(100),
   branch_strategy VARCHAR(100),
   clone_path VARCHAR(500),
   status VARCHAR(50) NOT NULL DEFAULT 'active',
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_repository PRIMARY KEY (id),
   CONSTRAINT fk_repository_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id)
);

-- changeset james.maes:0001-03
-- comment: Create agent table - persistent agent identity within a master project
CREATE TABLE agent (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT NOT NULL,
   repository_id BIGINT,
   name VARCHAR(200) NOT NULL,
   agent_type VARCHAR(50) NOT NULL,
   specialist_type VARCHAR(50),
   model_id VARCHAR(100) DEFAULT 'claude-sonnet-4-6',
   max_turns INTEGER DEFAULT 50,
   tool_permissions VARCHAR(2000),
   system_prompt_template TEXT,
   approval_policy VARCHAR(50) NOT NULL DEFAULT 'NONE',
   auto_approve_scope VARCHAR(10000),
   escalation_rules VARCHAR(10000),
   status VARCHAR(50) NOT NULL DEFAULT 'active',
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_agent PRIMARY KEY (id),
   CONSTRAINT fk_agent_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id),
   CONSTRAINT fk_agent_repository FOREIGN KEY (repository_id) REFERENCES repository (id)
);

-- changeset james.maes:0001-04
-- comment: Create agent_memory table - durable memory entries for agents
CREATE TABLE agent_memory (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   agent_id BIGINT NOT NULL,
   memory_type VARCHAR(50) NOT NULL,
   category VARCHAR(100),
   subject VARCHAR(500),
   content TEXT,
   relevance_score INTEGER DEFAULT 50,
   last_accessed_date TIMESTAMP WITHOUT TIME ZONE,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_agent_memory PRIMARY KEY (id),
   CONSTRAINT fk_agent_memory_agent FOREIGN KEY (agent_id) REFERENCES agent (id)
);

-- changeset james.maes:0001-05
-- comment: Create plan table - project-level or repository-level delivery plan
CREATE TABLE plan (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT NOT NULL,
   repository_id BIGINT,
   name VARCHAR(200) NOT NULL,
   goal VARCHAR(2000),
   approach VARCHAR(5000),
   steps_json TEXT,
   rollout_notes VARCHAR(5000),
   status VARCHAR(50) NOT NULL DEFAULT 'draft',
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_plan PRIMARY KEY (id),
   CONSTRAINT fk_plan_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id),
   CONSTRAINT fk_plan_repository FOREIGN KEY (repository_id) REFERENCES repository (id)
);

-- changeset james.maes:0001-06
-- comment: Create work_item table - maps to GitHub Issue or Jira ticket
CREATE TABLE work_item (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT NOT NULL,
   repository_id BIGINT,
   plan_id BIGINT,
   assigned_agent_id BIGINT,
   tracker_type VARCHAR(50) NOT NULL,
   tracker_project_key VARCHAR(200) NOT NULL,
   external_id VARCHAR(100) NOT NULL,
   external_url VARCHAR(500),
   item_type VARCHAR(50) NOT NULL,
   title VARCHAR(500) NOT NULL,
   status VARCHAR(50) NOT NULL,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_work_item PRIMARY KEY (id),
   CONSTRAINT fk_work_item_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id),
   CONSTRAINT fk_work_item_repository FOREIGN KEY (repository_id) REFERENCES repository (id),
   CONSTRAINT fk_work_item_plan FOREIGN KEY (plan_id) REFERENCES plan (id),
   CONSTRAINT fk_work_item_agent FOREIGN KEY (assigned_agent_id) REFERENCES agent (id)
);

-- changeset james.maes:0001-07
-- comment: Create agent_execution table - records each discrete agent execution
CREATE TABLE agent_execution (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   agent_id BIGINT NOT NULL,
   work_item_id BIGINT,
   task_prompt TEXT,
   prompt_hash VARCHAR(64),
   structured_output TEXT,
   tool_calls_summary TEXT,
   token_usage BIGINT,
   duration_ms BIGINT,
   cost_estimate VARCHAR(50),
   status VARCHAR(50) NOT NULL,
   execution_mode VARCHAR(50),
   started_at TIMESTAMP WITHOUT TIME ZONE,
   completed_at TIMESTAMP WITHOUT TIME ZONE,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_agent_execution PRIMARY KEY (id),
   CONSTRAINT fk_agent_execution_agent FOREIGN KEY (agent_id) REFERENCES agent (id),
   CONSTRAINT fk_agent_execution_work_item FOREIGN KEY (work_item_id) REFERENCES work_item (id)
);

-- changeset james.maes:0001-08
-- comment: Create work_item_link table - directed relationships between work items
CREATE TABLE work_item_link (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   source_work_item_id BIGINT NOT NULL,
   target_work_item_id BIGINT NOT NULL,
   link_type VARCHAR(50) NOT NULL,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_work_item_link PRIMARY KEY (id),
   CONSTRAINT fk_work_item_link_source FOREIGN KEY (source_work_item_id) REFERENCES work_item (id),
   CONSTRAINT fk_work_item_link_target FOREIGN KEY (target_work_item_id) REFERENCES work_item (id)
);

-- changeset james.maes:0001-09
-- comment: Create architecture_model table - versioned architecture snapshot
CREATE TABLE architecture_model (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT NOT NULL,
   name VARCHAR(200) NOT NULL,
   version VARCHAR(50) NOT NULL,
   source_type VARCHAR(50) NOT NULL,
   graph_json TEXT,
   description VARCHAR(2000),
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_architecture_model PRIMARY KEY (id),
   CONSTRAINT fk_architecture_model_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id)
);

-- changeset james.maes:0001-10
-- comment: Create architecture_component table - node in an architecture graph
CREATE TABLE architecture_component (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   architecture_model_id BIGINT NOT NULL,
   repository_id BIGINT,
   name VARCHAR(200) NOT NULL,
   component_type VARCHAR(50) NOT NULL,
   description VARCHAR(2000),
   metadata_json VARCHAR(10000),
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_architecture_component PRIMARY KEY (id),
   CONSTRAINT fk_architecture_component_model FOREIGN KEY (architecture_model_id) REFERENCES architecture_model (id),
   CONSTRAINT fk_architecture_component_repository FOREIGN KEY (repository_id) REFERENCES repository (id)
);

-- changeset james.maes:0001-11
-- comment: Create architecture_dependency table - directed edge between components
CREATE TABLE architecture_dependency (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   architecture_model_id BIGINT NOT NULL,
   source_component_id BIGINT NOT NULL,
   target_component_id BIGINT NOT NULL,
   dependency_type VARCHAR(50) NOT NULL,
   description VARCHAR(1000),
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_architecture_dependency PRIMARY KEY (id),
   CONSTRAINT fk_architecture_dependency_model FOREIGN KEY (architecture_model_id) REFERENCES architecture_model (id),
   CONSTRAINT fk_architecture_dependency_source FOREIGN KEY (source_component_id) REFERENCES architecture_component (id),
   CONSTRAINT fk_architecture_dependency_target FOREIGN KEY (target_component_id) REFERENCES architecture_component (id)
);

-- changeset james.maes:0001-12
-- comment: Create agent_message table - inter-agent communication records
CREATE TABLE agent_message (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT NOT NULL,
   sender_agent_id BIGINT NOT NULL,
   recipient_agent_id BIGINT NOT NULL,
   work_item_id BIGINT,
   message_type VARCHAR(50) NOT NULL,
   payload TEXT,
   referenced_artifacts VARCHAR(10000),
   status VARCHAR(50) NOT NULL DEFAULT 'pending',
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_agent_message PRIMARY KEY (id),
   CONSTRAINT fk_agent_message_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id),
   CONSTRAINT fk_agent_message_sender FOREIGN KEY (sender_agent_id) REFERENCES agent (id),
   CONSTRAINT fk_agent_message_recipient FOREIGN KEY (recipient_agent_id) REFERENCES agent (id),
   CONSTRAINT fk_agent_message_work_item FOREIGN KEY (work_item_id) REFERENCES work_item (id)
);

-- changeset james.maes:0001-13
-- comment: Create workflow table - durable orchestration workflow instance
CREATE TABLE workflow (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT NOT NULL,
   name VARCHAR(200) NOT NULL,
   workflow_type VARCHAR(50) NOT NULL,
   current_state VARCHAR(50) NOT NULL,
   waiting_on_condition VARCHAR(1000),
   context_json TEXT,
   started_at TIMESTAMP WITHOUT TIME ZONE,
   completed_at TIMESTAMP WITHOUT TIME ZONE,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_workflow PRIMARY KEY (id),
   CONSTRAINT fk_workflow_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id)
);

-- changeset james.maes:0001-14
-- comment: Create workflow_step table - individual step in a workflow
CREATE TABLE workflow_step (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   workflow_id BIGINT NOT NULL,
   step_order INTEGER NOT NULL,
   name VARCHAR(200) NOT NULL,
   step_type VARCHAR(50) NOT NULL,
   status VARCHAR(50) NOT NULL DEFAULT 'pending',
   input_json TEXT,
   output_json TEXT,
   approval_required BOOLEAN DEFAULT FALSE,
   approval_granted BOOLEAN,
   started_at TIMESTAMP WITHOUT TIME ZONE,
   completed_at TIMESTAMP WITHOUT TIME ZONE,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   modify_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_workflow_step PRIMARY KEY (id),
   CONSTRAINT fk_workflow_step_workflow FOREIGN KEY (workflow_id) REFERENCES workflow (id)
);

-- changeset james.maes:0001-15
-- comment: Create audit_entry table - immutable audit log for all system actions
CREATE TABLE audit_entry (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   master_project_id BIGINT,
   agent_id BIGINT,
   agent_execution_id BIGINT,
   work_item_id BIGINT,
   entity_type VARCHAR(100) NOT NULL,
   entity_id BIGINT,
   action VARCHAR(50) NOT NULL,
   details VARCHAR(10000),
   changes_json TEXT,
   create_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_audit_entry PRIMARY KEY (id),
   CONSTRAINT fk_audit_entry_master_project FOREIGN KEY (master_project_id) REFERENCES master_project (id),
   CONSTRAINT fk_audit_entry_agent FOREIGN KEY (agent_id) REFERENCES agent (id),
   CONSTRAINT fk_audit_entry_agent_execution FOREIGN KEY (agent_execution_id) REFERENCES agent_execution (id),
   CONSTRAINT fk_audit_entry_work_item FOREIGN KEY (work_item_id) REFERENCES work_item (id)
);
